### PR TITLE
Fix the Python package name

### PR DESCRIPTION
**Pull request by llucax**
The name should be `frequenz-client-dispatch` instead of `frequenz-dispatch-client`.

### CODE REVIEW

**Comment by llucax** [comment]
Fortunately there is no pypi release, so we don't need to fix anything in pypi.

**Comment by llucax** [comment]
@Marenz maybe it is a good time to make a pypi account and do a v0.1.0 release?

https://frequenz-floss.github.io/frequenz-repo-config-python/v0.10-dev/user-guide/start-a-new-project/configure-pypi/

**Review by Marenz — APPROVED** [review]

**Comment by Marenz** [comment]
No, both things already happened before your PR even :P

https://github.com/frequenz-floss/frequenz-client-dispatch-python/releases/tag/v0.1.0

However the releasing on pypi didn't work, probably because this PR was missing.

**Comment by llucax** [comment]
No, it failed because you are using git dependencies, pypi needs every dependency available in pypi:

https://github.com/frequenz-floss/frequenz-client-dispatch-python/actions/runs/8006394682/job/21869043552#step:4:26

I guess it is still a good thing that it failed.

**Comment by Marenz** [comment]
Oh right, I remember now :sweat_smile:

**Pull request merged**
